use std::path::Path;
use std::process::Command;

fn main() {
    // Run tauri-build
    tauri_build::build();

    // Only rebuild if UI source changes
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/src");
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/package.json");
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/openapi.json");

    // Check if we're in CI or should skip UI build
    if std::env::var("SKIP_UI_BUILD").is_ok() {
        println!("cargo:warning=Skipping UI build (SKIP_UI_BUILD set)");
        let assets_dir = Path::new("assets/spa");
        std::fs::create_dir_all(assets_dir).ok();
        return;
    }

    // Get paths
    let ui_dir = Path::new("../ensemble-ui/src-ui");
    let dist_dir = ui_dir.join("dist");
    let assets_dir = Path::new("assets/spa");

    // Check if UI source directory exists
    if !ui_dir.exists() {
        println!(
            "cargo:warning=UI source directory not found at {}",
            ui_dir.display()
        );
        println!("cargo:warning=Creating empty assets directory. UI will not be embedded.");
        std::fs::create_dir_all(assets_dir).ok();
        return;
    }

    // Check if pnpm/node is available
    if !command_exists("pnpm") {
        println!("cargo:warning=pnpm not found in PATH. UI will not be built.");
        println!("cargo:warning=Install pnpm (https://pnpm.io) or set SKIP_UI_BUILD=1 to skip.");
        std::fs::create_dir_all(assets_dir).ok();
        return;
    }

    // Check if openapi.json exists (generated by `pnpm run codegen:spec`)
    // We cannot run codegen:spec from build.rs because it invokes `cargo test`,
    // which would deadlock (cargo already holds the build lock).
    let openapi_json = ui_dir.join("openapi.json");
    if !openapi_json.exists() {
        panic!(
            "openapi.json not found at {}. Run `pnpm run codegen:spec` in crates/ensemble-ui/src-ui/ first, \
             or set SKIP_UI_BUILD=1 to skip the UI embed.",
            openapi_json.display()
        );
    }

    // Build the SPA (using build:embed which skips codegen:spec to avoid circular cargo dep)
    println!("cargo:warning=Building Ensemble UI for Desktop...");

    let pnpm_install = Command::new("pnpm")
        .args(["install", "--frozen-lockfile"])
        .current_dir(ui_dir)
        .status()
        .expect("Failed to run pnpm install");

    if !pnpm_install.success() {
        println!("cargo:warning=pnpm install failed");
        std::process::exit(1);
    }

    let pnpm_build = Command::new("pnpm")
        .args(["run", "build:embed"])
        .current_dir(ui_dir)
        .status()
        .expect("Failed to run pnpm build:embed");

    if !pnpm_build.success() {
        println!("cargo:warning=pnpm run build:embed failed");
        std::process::exit(1);
    }

    // Copy dist to assets
    std::fs::remove_dir_all(assets_dir).ok();
    std::fs::create_dir_all(assets_dir).unwrap();

    copy_dir_all(&dist_dir, assets_dir).expect("Failed to copy dist to assets");

    println!("cargo:warning=Ensemble Desktop UI built and embedded successfully");
}

fn command_exists(cmd: &str) -> bool {
    Command::new(cmd)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;

    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let dest_path = dst.join(entry.file_name());

        if path.is_dir() {
            copy_dir_all(&path, &dest_path)?;
        } else {
            std::fs::copy(&path, &dest_path)?;
        }
    }

    Ok(())
}
