use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_WEB_UI");

    if std::env::var("CARGO_FEATURE_WEB_UI").is_err() {
        return;
    }

    // Only rebuild if UI source changes
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/src");
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/package.json");
    println!("cargo:rerun-if-changed=../ensemble-ui/src-ui/openapi.json");

    // Check if we're in CI or should skip UI build
    if std::env::var("SKIP_UI_BUILD").is_ok() {
        println!("cargo:warning=Skipping UI build (SKIP_UI_BUILD set)");
        // Create empty assets directory if it doesn't exist
        let assets_dir = Path::new("assets/spa");
        std::fs::create_dir_all(assets_dir).ok();
        return;
    }

    // Get paths
    let ui_dir = Path::new("../ensemble-ui/src-ui");
    let dist_dir = ui_dir.join("dist");
    let assets_dir = Path::new("assets/spa");

    // Check if UI source directory exists
    if !ui_dir.exists() {
        println!(
            "cargo:warning=UI source directory not found at {}",
            ui_dir.display()
        );
        fail_missing_ui_assets(assets_dir);
    }

    // Check if pnpm/node is available
    if !command_exists("pnpm") {
        if prebuilt_spa_exists(assets_dir) {
            println!("cargo:warning=pnpm not found in PATH. Using existing embedded UI assets.");
            println!(
                "cargo:warning=Install pnpm to rebuild the UI, or set SKIP_UI_BUILD=1 to make reuse explicit."
            );
            return;
        }
        println!("cargo:warning=pnpm not found in PATH and no prebuilt UI assets were found.");
        fail_missing_ui_assets(assets_dir);
    }

    // Check if openapi.json exists (generated by `pnpm run codegen:spec`)
    // We cannot run codegen:spec from build.rs because it invokes `cargo test`,
    // which would deadlock (cargo already holds the build lock).
    let openapi_json = ui_dir.join("openapi.json");
    if !openapi_json.exists() {
        if prebuilt_spa_exists(assets_dir) {
            println!(
                "cargo:warning=openapi.json not found at {}. Using existing embedded UI assets.",
                openapi_json.display()
            );
            println!("cargo:warning=Run `pnpm run codegen:spec` in crates/ensemble-ui/src-ui/ to regenerate it.");
            return;
        }
        println!(
            "cargo:warning=openapi.json not found at {}. UI will not be embedded.",
            openapi_json.display()
        );
        println!("cargo:warning=Run `pnpm run codegen:spec` in crates/ensemble-ui/src-ui/ to generate it.");
        fail_missing_ui_assets(assets_dir);
    }

    // Build the SPA (using build:embed which skips codegen:spec to avoid circular cargo dep)
    println!("cargo:warning=Building Ensemble UI...");

    let pnpm_install = Command::new("pnpm")
        .args(["install", "--frozen-lockfile"])
        .current_dir(ui_dir)
        .status()
        .expect("Failed to run pnpm install");

    if !pnpm_install.success() {
        println!("cargo:warning=pnpm install failed");
        std::process::exit(1);
    }

    let pnpm_build = Command::new("pnpm")
        .args(["run", "build:embed"])
        .current_dir(ui_dir)
        .status()
        .expect("Failed to run pnpm build:embed");

    if !pnpm_build.success() {
        println!("cargo:warning=pnpm run build:embed failed");
        std::process::exit(1);
    }

    // Copy dist to assets
    std::fs::remove_dir_all(assets_dir).ok();
    std::fs::create_dir_all(assets_dir).unwrap();

    copy_dir_all(&dist_dir, assets_dir).expect("Failed to copy dist to assets");

    println!("cargo:warning=Ensemble UI built and embedded successfully");
}

fn command_exists(cmd: &str) -> bool {
    Command::new(cmd)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn prebuilt_spa_exists(assets_dir: &Path) -> bool {
    assets_dir.join("index.html").is_file()
}

fn fail_missing_ui_assets(assets_dir: &Path) -> ! {
    std::fs::create_dir_all(assets_dir).ok();
    panic!(
        "UI assets are unavailable. Install pnpm and generate the UI, provide prebuilt assets in {}, or set SKIP_UI_BUILD=1 for non-UI Rust checks.",
        assets_dir.display()
    );
}

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;

    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let dest_path = dst.join(entry.file_name());

        if path.is_dir() {
            copy_dir_all(&path, &dest_path)?;
        } else {
            std::fs::copy(&path, &dest_path)?;
        }
    }

    Ok(())
}
