[package]
name = "ensemble-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[[bin]]
name = "ensemble"
path = "src/main.rs"

[features]
default = ["open-config-dir"]
open-config-dir = ["dep:opener"]
web-ui = ["dep:axum", "dep:rust-embed"]

[dependencies]
ensemble-core = { path = "../ensemble-core" }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true, optional = true }
inquire = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
rust-embed = { workspace = true, optional = true }
reqwest = { workspace = true }
dirs = { workspace = true }
opener = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
wiremock = { workspace = true }
